# Set up the cms options
backend:
  name: git-gateway # Link the CMS with a Git repo
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img # Store uploaded images in this folder
public_folder: /img

# Define collections of content
collections:
  - name: "work" # Used in routes, e.g. admin/collections/work
    label: "Work" # Used in the UI
    folder: "src/pages/work" # Where the files will be stored
    create: true # Users can create new posts
    slug: "{{slug}}" # Creates a safe slug from the post's title
    fields: # The fields for each document
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "work-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Client", name: "client", widget: "string", required: true }
      - { label: "Image", name: "image", widget: "image", required: true }
      - {
          label: "Colours",
          name: "colours",
          widget: "string",
          default: "bg-near-black near-white",
          required: true,
          pattern:
            [
              "^(bg-[a-z-]+ [a-z-]+||[a-z-]+ bg-[a-z-]+)$",
              "Please provide two Tachyons classes for background and foreground colour",
            ],
        }
      - { label: "About", name: "about", widget: "text", required: true }
      - { label: "Order", name: "order", widget: "number", required: true }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featuredimage",
          widget: image,
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "about" # Used in routes, e.g. admin/collections/work
    label: "About" # Used in the UI
    folder: "src/pages/about" # Where the files will be stored
    create: true # Users can create new posts
    slug: "{{slug}}" # Creates a safe slug from the post's title
    fields: # The fields for each document
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "about-post",
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
